services:
  web:
    image: gestion-ev/extranet-web:1.1-dev
    build: .docker/web
    ports:
    - "${APP_PORT}:80"
    volumes:
    - .:/var/www/html
    - .docker/web/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
    - db
    - cache

  pma:
    image: phpmyadmin:latest
    ports:
    - "${PMA_PORT}:80"
    depends_on:
    - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  db:
    image: mysql:8.0
    ports:
    - "${DB_PORT}:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ev_extranet
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret

  cache:
    image: redis:7.0

volumes:
  mysql_data: